# Generated by Django 5.2.3 on 2025-07-30 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0002_alter_place_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionplace_kind",
            name="history",
        ),
        migrations.RemoveField(
            model_name="versionplace_kind",
            name="place",
        ),
        migrations.RemoveField(
            model_name="versionplace_kind",
            name="placecategory",
        ),
        migrations.DeleteModel(
            name="VersionPlace",
        ),
        migrations.DeleteModel(
            name="VersionPlace_kind",
        ),
    ]
