# Generated by Django 5.2.3 on 2025-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0004_versionplace_versionplace_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="history",
            new_name="place_history",
        ),
        migrations.RenameField(
            model_name="versionplace",
            old_name="history",
            new_name="place_history",
        ),
    ]
