# Generated by Django 5.2.3 on 2025-07-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0005_rename_history_place_place_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.eventcategory", verbose_name="Category"
            ),
        ),
    ]
