# Generated by Django 5.2.3 on 2025-07-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0006_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                default="",
                max_length=4096,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                default="",
                max_length=4096,
                verbose_name="Gender",
            ),
        ),
    ]
