# Generated by Django 5.2.3 on 2025-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0007_alter_person_gender_alter_versionperson_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
