# Generated by Django 5.2.5 on 2026-01-25 23:51

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0008_title_abbreviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glossar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="label"
                    ),
                ),
                ("definition", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Glossary",
                "verbose_name_plural": "Glossary",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={},
        ),
        migrations.AlterField(
            model_name="place",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="abbreviation",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Abbreviation"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AddField(
            model_name="bureau",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="bureauactiveatplace",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="eventinvolvedbureau",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="eventoccuredatplace",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="importantmomentinanevent",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personactiveatplace",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personborninplace",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="persondiedinplace",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personparentof",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personparticipatedinevent",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personpartnerof",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personrelatedto",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personsiblingof",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="personworkedforbureau",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="glossar_terms",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.glossar", verbose_name="Glossary terms"
            ),
        ),
        migrations.CreateModel(
            name="VersionBureau_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bureau",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.bureau",
                    ),
                ),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionbureau",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionBureau_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionBureauActiveAtPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bureauactiveatplace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.bureauactiveatplace",
                    ),
                ),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionbureauactiveatplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionBureauActiveAtPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionEvent_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.event",
                    ),
                ),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionEvent_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionEventInvolvedBureau_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "eventinvolvedbureau",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.eventinvolvedbureau",
                    ),
                ),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versioneventinvolvedbureau",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionEventInvolvedBureau_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionEventOccuredAtPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "eventoccuredatplace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.eventoccuredatplace",
                    ),
                ),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versioneventoccuredatplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionEventOccuredAtPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionImportantMomentInAnEvent_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionimportantmomentinanevent",
                    ),
                ),
                (
                    "importantmomentinanevent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.importantmomentinanevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionImportantMomentInAnEvent_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPerson_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionperson",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPerson_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonActiveAtPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonactiveatplace",
                    ),
                ),
                (
                    "personactiveatplace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personactiveatplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonActiveAtPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonBornInPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonborninplace",
                    ),
                ),
                (
                    "personborninplace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personborninplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonBornInPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonDiedInPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersondiedinplace",
                    ),
                ),
                (
                    "persondiedinplace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.persondiedinplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonDiedInPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonParentOf_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonparentof",
                    ),
                ),
                (
                    "personparentof",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personparentof",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonParentOf_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonParticipatedInEvent_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonparticipatedinevent",
                    ),
                ),
                (
                    "personparticipatedinevent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personparticipatedinevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonParticipatedInEvent_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonPartnerOf_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonpartnerof",
                    ),
                ),
                (
                    "personpartnerof",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personpartnerof",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonPartnerOf_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonRelatedTo_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonrelatedto",
                    ),
                ),
                (
                    "personrelatedto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personrelatedto",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonRelatedTo_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonSiblingOf_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonsiblingof",
                    ),
                ),
                (
                    "personsiblingof",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personsiblingof",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonSiblingOf_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPersonWorkedForBureau_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionpersonworkedforbureau",
                    ),
                ),
                (
                    "personworkedforbureau",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.personworkedforbureau",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPersonWorkedForBureau_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionPlace_glossar_terms",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "glossar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.glossar",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionplace",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionPlace_glossar_terms",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
