# Generated by Django 5.2.5 on 2026-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0012_add_bionote"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="attended_military_basic_education",
            field=models.BooleanField(
                default=False, verbose_name="Attended military basic education"
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="attended_military_basic_education",
            field=models.BooleanField(
                default=False, verbose_name="Attended military basic education"
            ),
        ),
    ]
