# Generated by Django 5.2.5 on 2026-04-30 07:25

import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_metainfo", "0017_delete_uri"),
        ("apis_ontology", "0014_nobility_versionnobility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HonoursEntity",
            fields=[
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "rootobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="label"
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(
                        blank=True, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(
                        blank=True, null=True, verbose_name="End"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                (
                    "donour",
                    models.ManyToManyField(
                        to="apis_ontology.person", verbose_name="Donour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Honours",
                "verbose_name_plural": "Honours",
                "ordering": ["label"],
                "abstract": False,
            },
            bases=("apis_metainfo.rootobject", models.Model),
        ),
        migrations.CreateModel(
            name="VersionHonoursEntity",
            fields=[
                (
                    "rootobject_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=4096, verbose_name="label"
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(
                        blank=True, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(
                        blank=True, null=True, verbose_name="End"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="Purpose"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Honours",
                "verbose_name_plural": "historical Honours",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionHonoursEntity_donour",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apis_ontology.versionhonoursentity",
                    ),
                ),
                (
                    "honoursentity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.honoursentity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="apis_ontology.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "VersionHonoursEntity_donour",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
