# Generated by Django 5.2.5 on 2026-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0018_create_personhashonours_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="honours",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                to="apis_ontology.honours",
                verbose_name="Honours",
            ),
        ),
    ]
