# Generated by Django 5.2.5 on 2026-04-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0019_alter_person_honours"),
    ]

    operations = [
        migrations.AddField(
            model_name="personhashonours",
            name="in_relation_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_ontology.event",
                verbose_name="In relation to event",
            ),
        ),
        migrations.AddField(
            model_name="versionpersonhashonours",
            name="in_relation_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.event",
                verbose_name="In relation to event",
            ),
        ),
    ]
