# Generated by Django 5.2.5 on 2026-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0020_personhashonours_in_relation_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Label"
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="label",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Label"
            ),
        ),
    ]
