# Generated by Django 5.2.5 on 2026-09-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0021_event_description_versionevent_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nobility",
            options={
                "ordering": ["label"],
                "verbose_name": "Nobility",
                "verbose_name_plural": "nobilities",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="versionnobility",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Nobility",
                "verbose_name_plural": "historical nobilities",
            },
        ),
    ]
